"""initial partitioned clicks table

Revision ID: 0001
Revises:
Create Date: 2026-06-08

Hand-written rather than autogenerated: Alembic's autogenerate does not emit
the ``PARTITION BY`` clause or the DEFAULT partition, both of which are
essential here (see README "Archiving old data").
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "clicks",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("shop_url", sa.Text(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # The partition key (timestamp) must be part of the primary key.
        sa.PrimaryKeyConstraint("id", "timestamp"),
        postgresql_partition_by="RANGE (timestamp)",
    )
    op.create_index(
        "clicks_user_id_timestamp_idx",
        "clicks",
        ["user_id", sa.text("timestamp DESC")],
    )
    # Catch-all partition so inserts never fail if a dated partition is missing.
    # In production a scheduler (pg_partman / cron) pre-creates daily partitions.
    op.execute("CREATE TABLE clicks_default PARTITION OF clicks DEFAULT")


def downgrade() -> None:
    # Dropping the partitioned parent removes the default partition with it.
    op.drop_index("clicks_user_id_timestamp_idx", table_name="clicks")
    op.drop_table("clicks")
